#ifndef ProjectConstants_CPP
#define ProjectConstants_CPP

#define BUFFER_WEATHER_API 2048
#define CONST_NORMAL 1
#define CONST_DOUBLE 2
#define CONST_TRIPLE 3
#define WINDOW_CLASS_STATIC L"STATIC"
#define WINDOW_CLASS_EDIT L"EDIT"
#define WIN_TYPE_LABEL 0
#define WIN_TYPE_ERROR 1
#define WIN_TYPE_HEADER 2
#define WIN_TYPE_EDIT 3
#define MAIN_WINDOW_WIDTH 500
#define MAIN_WINDOW_HEIGHT 600 
#define CONTROL_POSITION_ROW_COUNT 3
#define CONTROL_POSITION_X_DEFAULT 50
#define CONTROL_POSITION_Y_DEFAULT 50
#define CONTROL_GAP_XY 5
#define CONTROL_WIDTH_NORMAL 100
#define CONTROL_WIDTH_DOUBLE (CONTROL_WIDTH_NORMAL * 2) + CONTROL_GAP_XY
#define CONTROL_WIDTH_TRIPLE (CONTROL_WIDTH_NORMAL * 3) + CONTROL_GAP_XY 
#define CONTROL_HEIGHT_NORMAL 20
#define CONTROL_HEIGHT_DOUBLE (CONTROL_HEIGHT_NORMAL * 2) + CONTROL_GAP_XY
#define CONTROL_HEIGHT_TRIPLE (CONTROL_HEIGHT_NORMAL * 3) + CONTROL_GAP_XY

// META Id Info
#define RANGE_IDS_GAP 99
#define RANGE_IDS_STATIC_LABEL 100
#define RANGE_IDS_STATIC_ERROR 200
#define RANGE_IDS_STATIC_HEADER 300
#define RANGE_IDS_EDIT 400
#define RANGE_IDS_BUTTON 500
// Control Ids
#define ID_STATIC_LABEL_ONE 101
#define ID_STATIC_LABEL_TWO 102
#define ID_STATIC_ERROR_ONE 201
#define ID_STATIC_ERROR_TWO 202
#define ID_STATIC_HEADER_ONE 301
#define ID_STATIC_HEADER_TWO 302

#endif